name:                two-knights
version:             0.1.0.0
github:              "https://github.com/Cthaeeh/two-knights"
license:             BSD3
author:              "Kai Hofmann"
maintainer:          "example@example.com"
copyright:           "2021 Kai Hofmann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Cthaeeh/two-knights#readme>

dependencies:
- base >= 4.7 && < 5
- containers 


library:
  source-dirs: src

executables:
  two-knights-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - two-knights

tests:
  two-knights-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - two-knights
